I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 84, in script
    start music "Gameover.mp3"
Exception: Sayer 'start' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 84, in script
    start music "Gameover.mp3"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'start' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
From Ends of the World 1.0
Tue Sep 14 16:16:56 2021
